default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        exclude: ".*/migrations/.*"
        args: ["--line-length=91"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.3.2
    hooks:
      - id: isort
        exclude: |
          (?x)(
            ^.*/migrations/.*
          )

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
